baseURL = 'https://antoniobiasotti.github.io/'
languageCode = 'en-us'
title = 'Antônio Biasotti'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A tech-oriented personal blog curated by Antônio Biasotti."

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = ''
homeIntroContent = """
Sou um estudante de Sistemas de Informação
apaixonado por Ciência de Dados e Inteligência Artificial. No momento escrevo minha tese, um framework estratégico para Governança de IA no Brasil
que garanta segurança jurídica e liberdade econômica.

Fique à vontade para se conectar ou ler meus [posts](/posts).
"""


singleDateFormat = '2 Jan 2006'

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = true

showFooter = true
# footerContent = """Custom"""

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/antonio-biasotti/"

[[params.social]]
name = "github"
url = "https://github.com/antoniobiasotti"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "coursework"
url = "/coursework"

[[params.menu]]
name = "posts"
url = "/posts"

# [[params.menu]]
# name = "tags"
# url = "/tags"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'bw'

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[params.giscus]
enable = false
repo = "tomfran/blog"
repoid = "R_kgDOLtSszw"
category = "General"
categoryid = "DIC_kwDOLtSsz84CfLm4"
mapping = "pathname"
theme = "preferred_color_scheme"

[params.umami]
enable = true
websiteId = "cc219028-551e-4f3b-bbc7-e124ca907ce0"
jsLocation = "https://cloud.umami.is/script.js"
